import polars as pl
from typing import Any as Incomplete
from srcPy.ops.mm_logkit import get_logger as get_logger
from srcPy.pipeline.core.pipeline_core_metrics import AsyncMLflowLogger as AsyncMLflowLogger, buffer_length as buffer_length, data_volume as data_volume, streaming_step_latency as streaming_step_latency
from srcPy.pipeline.stages.cleaning.core.base import CleaningStep as CleaningStep
from srcPy.utils.config import get_config as get_config
from srcPy.utils.exceptions import DataValidationError as DataValidationError
from srcPy.utils.validators import validate_stream_chunk as validate_stream_chunk
from typing import AsyncGenerator

logger: Incomplete = ...

class StreamingCleanerPipeline:
    """streaming cleaner pipeline class."""
    steps: Incomplete = ...
    mlflow_logger: Incomplete = ...
    buffer: Incomplete = ...
    buffer_size: Incomplete = ...
    window: Incomplete = ...
    config: Incomplete = ...
    def __init__(self, steps: list[CleaningStep], buffer_size: int = 100, window: int = 252) -> None: ...
    def adjust_buffer_size(self, latency: float): ...
    async def process_stream(self, stream_gen: AsyncGenerator[pl.DataFrame, None]) -> AsyncGenerator[pl.DataFrame, None]: ...
    def close(self) -> None: ...