import logging
import logging.handlers
import queue
import structlog
from typing import Any as Incomplete
from dataclasses import dataclass
from typing import Any, Iterable, Mapping

__all__ = ['BoundLogger', 'configure_logger', 'get_logger', 'JSONFormatter', 'KVFormatter', 'RedactFilter', 'redact_processor', 'redact_sensitive_info', 'timestamp_processor', 'safe_filter_by_level', 'build_console_handler', '_set_handler_level', 'build_file_handler', 'build_syslog_handler', 'build_http_handler', 'build_influx_handler', 'InfluxDBHandler', 'log_drift_warning']

class DefaultCredentialsError(Exception): ...

class RedactFilter(logging.Filter):
    """redact filter class."""
    def __init__(self, keys: Iterable[str] = ...) -> None: ...
    def filter(self, record: logging.LogRecord) -> bool: ...

def redact_processor(_, __, event_dict: dict[str, Any]) -> dict[str, Any]: ...
def redact_sensitive_info(keys: Iterable[str]): ...
def timestamp_processor(_, __, event_dict: dict[str, Any]) -> dict[str, Any]: ...
def safe_filter_by_level(logger: logging.Logger | None, level: str, event_dict: dict[str, Any]) -> dict[str, Any]: ...

class JSONFormatter(logging.Formatter):
    """json formatter class."""
    def format(self, record: logging.LogRecord) -> str: ...

class KVFormatter(logging.Formatter):
    """kv formatter class."""
    def format(self, record: logging.LogRecord) -> str: ...

class LogRecorder:
    """log recorder class."""
    logger_name: Incomplete = ...
    records: list[tuple[str, int]] = ...
    handler: logging.Handler | None = ...
    logger: logging.Logger | None = ...
    old_level: int | None = ...
    old_propagate: bool | None = ...
    def __init__(self, logger_name: str | None = None) -> None: ...
    def __enter__(self) -> LogRecorder: ...
    def __exit__(self, *args: Any) -> None: ...
    def has_message(self, substring: str, level: int | None = None) -> bool: ...

class _HandlerRegistry:
    """handler registry class."""
    def __init__(self) -> None: ...
    def register(self, logger_name: str, handler: logging.Handler) -> None: ...
    def is_ours(self, logger_name: str, handler: logging.Handler) -> bool: ...

class _StdBoundLogger(structlog.BoundLogger): ...
class _StdBoundLogger: ...

class BoundLogger(_StdBoundLogger):
    """bound logger class."""
    def __init__(self, logger: logging.Logger, processors: list | None = None, context: dict[str, Any] | None = None) -> None: ...
    @property
    def name(self) -> str: ...
    def setLevel(self, level: Any) -> None: ...
    def bind(self, **context: Any) -> BoundLogger: ...
    def debug(self, msg: str, *a: Any, **k: Any) -> None: ...
    def info(self, msg: str, *a: Any, **k: Any) -> None: ...
    def warning(self, msg: str, *a: Any, **k: Any) -> None: ...
    def error(self, msg: str, *a: Any, **k: Any) -> None: ...
    def critical(self, msg: str, *a: Any, **k: Any) -> None: ...
    def exception(self, msg: str, *a: Any, **k: Any) -> None: ...
    def DEBUG(self, *args: Any, **kwargs: Any) -> None: ...
    def INFO(self, *args: Any, **kwargs: Any) -> None: ...
    def WARNING(self, *args: Any, **kwargs: Any) -> None: ...
    def ERROR(self, *args: Any, **kwargs: Any) -> None: ...
    def CRITICAL(self, *args: Any, **kwargs: Any) -> None: ...
    def EXCEPTION(self, *args: Any, **kwargs: Any) -> None: ...

@dataclass
class _AsyncState:
    """async state class."""
    q: queue.Queue[logging.LogRecord] = ...
    listener: logging.handlers.QueueListener = ...
    started: bool = ...

def _set_handler_level(handler: logging.Handler, level: Any) -> None: ...
def build_console_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_file_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_syslog_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_http_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_influx_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...

class _InfluxDBHandler(logging.Handler):
    """Handles influx db events and requests."""
    def __init__(self, spec: Mapping[str, Any]) -> None: ...
    def emit(self, record: logging.LogRecord) -> None: ...

def configure_logger(config: dict | str | None = None, /, **legacy_kwargs: Any) -> BoundLogger | None: ...
def get_logger(name: str | None = None) -> BoundLogger: ...
def log_drift_warning(*args: Any, **kwargs: Any) -> None: ...

class InfluxDBHandler(logging.Handler):
    """Handles influx db events and requests."""
    client: Incomplete = ...
    write_api: Incomplete = ...
    def __init__(self, client: Any | None, bucket: str, org: str) -> None: ...
    def emit(self, record: logging.LogRecord) -> None: ...
    def handleError(self, record: logging.LogRecord) -> None: ...