version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - apt-get update && apt-get install -y git

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py   # ← updated path
  fail_on_warning: false

formats:
  - pdf
  - epub
