from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Any, Callable

__all__ = ['Backend', 'ModelRegistry', 'Plan', 'PlanSpec', 'Preprocessor', 'PreprocessorBuilder', 'build_plan_from_spec', 'compile_plan', 'get_executor', 'merge_specs', 'resolve_models_in_ops', 'run', 'stream']

Backend: Incomplete

class Preprocessor:
    backend: Incomplete
    def __init__(self, backend: str = 'polars') -> None: ...
    def materialize(self, df, spec) -> tuple: ...

@dataclass
class PlanSpec:
    ops: list[dict[str, Any]] = field(default_factory=list)
    target: dict[str, Any] | None = ...
    sequence: dict[str, Any] | None = ...
    scaling: dict[str, Any] | None = ...
    meta: dict[str, Any] | None = ...

def merge_specs(*specs: PlanSpec) -> PlanSpec: ...

class ModelRegistry:
    @classmethod
    def register(cls, name: str, obj: Any): ...
    @classmethod
    def get(cls, name: str) -> Any: ...

def resolve_models_in_ops(ops: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

@dataclass(frozen=True)
class Plan:
    ops: list[str]
    params: dict[str, list[dict[str, Any]]]
    group_by: list[str]
    version: str = ...

def get_executor(backend: Backend = 'auto'): ...
def run(df: Any, plan: Plan | dict[str, Any], *, backend: Backend = 'auto', optimize: bool | None = None, pressure: str | None = None, **_ignored) -> Any: ...
def stream(plan: Plan, *, backend: Backend = 'auto'): ...

class PreprocessorBuilder:
    def __init__(self, backend: Backend = 'auto') -> None: ...
    def add_op(self, op_symbol: str, **params) -> PreprocessorBuilder: ...
    def set_group_by(self, cols: list[str]) -> PreprocessorBuilder: ...
    def set_backend(self, backend: Backend) -> PreprocessorBuilder: ...
    def from_dict(self, cfg: dict[str, Any]) -> PreprocessorBuilder: ...
    def build_plan(self) -> Plan: ...
    def build_runner(self) -> Callable[[Any], Any]: ...
    def add_dsl_op(self, op_symbol: str, backend_hint: str = None, **params) -> PreprocessorBuilder: ...
    def add_sequence(self, *ops: str | dict[str, Any]) -> PreprocessorBuilder: ...
    def add_parallel(self, *builders: PreprocessorBuilder) -> PreprocessorBuilder: ...
    def add_transform(self, transform_name: str, **params) -> PreprocessorBuilder: ...

def build_plan_from_spec(*args, **kwargs) -> None: ...
def compile_plan(*args, **kwargs) -> None: ...
