# from .transforms import build_steps as build_steps  # stripped for AutoAPI
from typing import Any as Incomplete
from polars import LazyFrame as LazyFrame
from pydantic import BaseModel
from srcPy.ops.caching import ttl_cache as ttl_cache
from srcPy.ops.mm_logkit import get_logger as get_logger
from srcPy.pipeline.core.pipeline_core_base import PipelineStep as PipelineStep
from srcPy.utils.exceptions import DataValidationError as DataValidationError
from typing import Callable

logger: Incomplete = ...

class AnonymizationConfig(BaseModel):
    """Configuration for anonymization."""
    enabled: bool = ...
    sensitive_columns: list[str] = ...
    hash_algorithm: str = ...
    salt: str | None = ...

def get_hash_func(algo: str, salt: str | None = None) -> Callable[[str], str]: ...

class DataAnonymizationStep(PipelineStep):
    """data anonymization step class."""
    config: Incomplete = ...
    hasher: Incomplete = ...
    def __init__(self, config: AnonymizationConfig) -> None: ...
    def apply(self, lf: LazyFrame) -> LazyFrame: ...

class RegulatoryFilterConfig(BaseModel):
    """Configuration for regulatory filter."""
    enabled: bool = ...
    restricted_symbols: list[str] = ...
    min_volume_threshold: float | None = ...

class RegulatoryFilterStep(PipelineStep):
    """regulatory filter step class."""
    config: Incomplete = ...
    def __init__(self, config: RegulatoryFilterConfig) -> None: ...
    def apply(self, lf: LazyFrame) -> LazyFrame: ...

COMPLIANCE_STEPS: dict[str, type[PipelineStep]] = ...
COMPLIANCE_CONFIGS: dict[str, type[BaseModel]] = ...

def build_compliance_steps(configs: list[dict]) -> list[PipelineStep]: ...