from typing import Any

__all__ = ['to_polars', 'ensure_datetime_col', 'infer_ticker_col', 'normalize_fetched']

def to_polars(df: Any) -> Any: ...
def ensure_datetime_col(df: Any, date_col: str = 'date') -> Any: ...
def infer_ticker_col(df: Any) -> str | None: ...
def normalize_fetched(obj: Any) -> Any: ...