import types
from _typeshed import Incomplete
from dataclasses import dataclass
from typing import Any, ContextManager, TypeVar

__all__ = ['deps', 'Counter', 'Gauge', 'Histogram', 'Summary', 'pydantic_dataclass', 'ConfigDict', 'ensure_pandas', 'ensure_polars', 'ensure_numpy', 'ensure_dask_dataframe', 'ensure_sklearn', 'ensure_isolation_forest', 'ensure_parameter_grid', 'ensure_cudf', 'ensure_cupy', 'ensure_cuml', 'ensure_robust_scaler', 'ensure_mlflow', 'ensure_prometheus_client', 'ensure_influxdb_client', 'ensure_watchtower', 'ensure_gcloud_logging', 'ensure_pydantic', 'ensure_aiohttp']

T = TypeVar('T')
deps: DependencyManager | None
Counter: Incomplete
Gauge: Incomplete
Histogram: Incomplete
Summary: Incomplete
pydantic_dataclass: Incomplete
ConfigDict: Incomplete

class _NoopMetric:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def labels(self, *args: Any, **kwargs: Any) -> _NoopMetric: ...
    def inc(self, *args: Any, **kwargs: Any) -> None: ...
    def observe(self, *args: Any, **kwargs: Any) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def set_to_current_time(self, *args: Any, **kwargs: Any) -> None: ...
    def start_timer(self, *args: Any, **kwargs: Any) -> _NoopMetric: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> None: ...
    def time(self) -> ContextManager[None]: ...

class _NoopPydantic:
    @staticmethod
    def dataclass(*args: Any, **kwargs: Any): ...
    ConfigDict = dict

@dataclass(frozen=True)
class _Dependency:
    module_path: str
    pip_name: str
    purpose: str
    obj_name: str | None = ...
    min_version: str | None = ...

class DependencyManager:
    def __new__(cls, *a: Any, **k: Any) -> DependencyManager: ...
    def __init__(self, config: dict[str, _Dependency]) -> None: ...
    def has(self, key: str) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def ensure(self, key: str) -> Any: ...
    def __getattr__(self, key: str) -> Any: ...

def ensure_pandas() -> types.ModuleType: ...
def ensure_polars() -> types.ModuleType: ...
def ensure_numpy() -> types.ModuleType: ...
def ensure_dask_dataframe() -> types.ModuleType: ...
def ensure_sklearn() -> types.ModuleType: ...
def ensure_isolation_forest() -> Any: ...
def ensure_parameter_grid() -> Any: ...
def ensure_cudf() -> types.ModuleType: ...
def ensure_cupy() -> types.ModuleType: ...
def ensure_cuml() -> types.ModuleType: ...
def ensure_robust_scaler() -> Any: ...
def ensure_mlflow() -> types.ModuleType: ...
def ensure_prometheus_client() -> types.ModuleType: ...
def ensure_influxdb_client() -> Any: ...
def ensure_watchtower() -> types.ModuleType: ...
def ensure_gcloud_logging() -> types.ModuleType: ...
def ensure_pydantic() -> types.ModuleType: ...
def ensure_aiohttp() -> types.ModuleType: ...
