import abc
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

class ErrorCodeEnum(str, Enum):
    GENERIC = 'GENERIC_ERROR'
    DATA_FETCH = 'DATA_FETCH_ERROR'
    API_CONNECTION = 'API_CONNECTION_ERROR'
    STREAM_CONNECTION = 'STREAM_CONNECTION_ERROR'
    DATA_TIMEOUT = 'DATA_TIMEOUT_ERROR'
    DATA_VALIDATION = 'DATA_VALIDATION_ERROR'
    SCHEMA_VALIDATION = 'SCHEMA_VALIDATION_ERROR'
    FILE_FORMAT = 'FILE_FORMAT_ERROR'
    STATISTICAL_TEST = 'STATISTICAL_TEST_ERROR'
    DATA_DRIFT = 'DATA_DRIFT_ERROR'
    NO_DATA = 'NO_DATA_ERROR'
    CONFIG_VALIDATION = 'CONFIG_VALIDATION_ERROR'
    PREPROCESSING = 'PREPROCESSING_ERROR'
    MODEL_TRAINING = 'MODEL_TRAINING_ERROR'
    TRADING_EXECUTION = 'TRADING_EXECUTION_ERROR'
    INVALID_INPUT = 'INVALID_INPUT_ERROR'
    MODEL_CHECKPOINT = 'MODEL_CHECKPOINT_ERROR'
    MODEL_INFERENCE = 'MODEL_INFERENCE_ERROR'
    UNSUPPORTED_PLAN = 'UNSUPPORTED_PLAN'

@dataclass
class _ErrorStorm:
    timestamps: list[float] = field(default_factory=list)
    suppressed: int = ...

class _RateLimiter:
    def __init__(self, window_sec: float, threshold: int) -> None: ...
    def should_log(self, code: str) -> bool: ...
    def suppressed_count(self, code: str) -> int: ...

class BaseError(RuntimeError):
    msg: Incomplete
    code: Incomplete
    details: Incomplete
    __cause__: Incomplete
    def __init__(self, msg: str, *, code: str | None = None, details: dict[str, Any] | None = None, cause: BaseException | None = None) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class UnsupportedPlan(BaseError):
    def __init__(self, msg: str = 'Unsupported execution plan', **kwargs: Any) -> None: ...

class DataError(BaseError, ABC, metaclass=abc.ABCMeta):
    def __init__(self, message: str, details: dict[str, Any] | None = None) -> None: ...
    @abstractmethod
    def get_error_code(self) -> str: ...

class GenericDataError(DataError):
    def __init__(self, message: str = 'An error occurred', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class ExceptionRegistry:
    @classmethod
    def register(cls, error_type: str, exception_class: type[DataError]) -> None: ...
    @classmethod
    def get_exception(cls, error_type: str, message: str, details: dict[str, Any] | None = None) -> DataError: ...

class AggregateError(DataError):
    errors: Incomplete
    def __init__(self, message: str = 'Multiple errors occurred', errors: list[DataError] | None = None) -> None: ...
    def get_error_code(self) -> str: ...
    def add_error(self, error: DataError) -> None: ...

class DataFetchError(DataError):
    def __init__(self, message: str = 'Data fetch failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class APIConnectionError(DataFetchError):
    def __init__(self, message: str = 'Failed to connect to API', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class StreamConnectionError(DataFetchError):
    def __init__(self, message: str = 'Failed to connect to streaming source', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class DataTimeoutError(DataFetchError):
    def __init__(self, message: str = 'Data fetch timed out', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class DataValidationError(DataError):
    class Code(str, Enum):
        MISSING_COLUMNS = 'MISSING_COLUMNS'
        INVALID_TYPE = 'INVALID_TYPE'
        EMPTY_DATA = 'EMPTY_DATA'
        SCHEMA_MISMATCH = 'SCHEMA_MISMATCH'
        FILE_FORMAT = 'FILE_FORMAT'
    codes: Incomplete
    def __init__(self, message: str = 'Data validation failed', codes: list['DataValidationError.Code'] | None = None, details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class SchemaValidationError(DataValidationError):
    def __init__(self, message: str = 'Schema validation failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class FileFormatError(DataValidationError):
    def __init__(self, message: str = 'Invalid/unsupported file format', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class StatisticalTestError(DataError):
    def __init__(self, message: str = 'Statistical test failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class DataDriftError(StatisticalTestError):
    def __init__(self, message: str = 'Data drift detected', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class IBKRConnectionError(StreamConnectionError):
    def __init__(self, message: str = 'Failed to connect to Interactive Brokers', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class NoDataError(DataFetchError):
    def __init__(self, symbol: str, details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class ConfigValidationError(DataError):
    def __init__(self, message: str = 'Configuration validation failed', validation_errors: list[str] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class PreprocessingError(DataError):
    def __init__(self, message: str = 'Data preprocessing failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class ModelTrainingError(DataError):
    def __init__(self, message: str = 'Model training failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class TradingExecutionError(DataError):
    def __init__(self, message: str = 'Trading execution failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class InvalidInputError(DataError):
    def __init__(self, message: str = 'Invalid input data', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class ModelCheckpointError(DataError):
    def __init__(self, message: str = 'Model checkpointing failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...

class ModelInferenceError(DataError):
    def __init__(self, message: str = 'Model inference failed', details: dict[str, Any] | None = None) -> None: ...
    def get_error_code(self) -> str: ...
