from typing import Any, Callable, Iterable

def parameter_grid_iter(grid: list[dict[str, Iterable]]) -> Iterable[dict[str, Any]]: ...
def optuna_search(preset: dict[str, Any], grid: list[dict[str, Iterable]], eval_fn: Callable[[dict[str, Any]], float], *, direction: str = 'minimize', n_trials: int = 50, sampler=None, pruner=None, study_name: str | None = None, storage: str | None = None) -> dict[str, Any]: ...
