from _typeshed import Incomplete
from scipy.optimize import minimize_scalar as minimize_scalar

class RiskManager:
    p_bins: Incomplete
    R_avg: Incomplete
    L_avg: Incomplete
    def __init__(self) -> None: ...
    def update_historical_data(self, p: float, r: float) -> None: ...
    def get_R_L_for_p(self, p: float) -> tuple[float, float]: ...
    def calculate_kelly_fraction(self, p: float) -> float: ...

def get_trailing_stop_loss(entry_price: float, current_price: float, max_price: float, trail_percent: float = 0.02) -> tuple[float, float]: ...
def check_drawdown(current_balance: float, max_balance: float, threshold: float = 0.2) -> bool: ...
