import torch
from contextlib import contextmanager
from torch import nn
from typing import Literal

__all__ = ['seed_everything', 'init_weights', 'autocast', 'get_device', 'set_perf_flags', 'set_logging_level']

def set_logging_level(level: Literal['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']) -> None: ...
def set_perf_flags(precision_flags: dict[str, bool | str] | None = None) -> None: ...
def seed_everything(seed: int = 42, *, deterministic: bool = True, warn_only: bool = False, precision_flags: dict[str, bool | str] | None = None, return_generator: bool = False) -> torch.Generator | None: ...
def init_weights(module: nn.Module, mode: Literal['xavier_uniform', 'xavier_normal', 'kaiming_uniform', 'kaiming_normal', 'orthogonal', 'trunc_normal'] = 'xavier_uniform', generator: torch.Generator | None = None) -> None: ...
def get_device(preferred_idx: int | None = None) -> torch.device: ...
@contextmanager
def autocast(enabled: bool = True, dtype: torch.dtype = ..., device_type: Literal['cuda', 'cpu', 'mps'] | None = None): ...