import abc
import pandas as pd
from typing import Any as Incomplete
from abc import ABC, abstractmethod
from functools import singledispatch
from typing import Any, Callable, Protocol, Sequence

__all__ = ['validate_series', 'validate_dataframe', 'validate_ohlcv', 'validate_stream_chunk', 'validate_data_for_training', 'validate_symbol', 'validate_date', 'validate_tensor', 'Validator', 'compose_validators', 'all_of', 'any_of', 'register_validator', 'validate_file_data', 'lazy_validate_ohlcv']

class _NS:
    """ns class."""
    pd: Incomplete = ...
    pl: Incomplete = ...
    cudf: Incomplete = ...
    def __init__(self) -> None: ...

def validate_dataframe(df: Any, *, required_cols: Sequence[str] | None = None, allow_lazy: bool = True) -> None: ...
def lazy_validate_ohlcv(df) -> bool: ...

class SeriesLike(Protocol):
    """series like class."""
    def is_empty(self) -> bool: ...
    def null_count(self) -> int: ...
    def len(self) -> int: ...

class DataFrameLike(Protocol):
    """data frame like class."""
    def is_empty(self) -> bool: ...
    @property
    def columns(self) -> list[str]: ...
    @property
    def schema(self) -> dict: ...

class TensorLike(Protocol):
    """tensor like class."""
    @property
    def ndim(self) -> int: ...
    def numel(self) -> int: ...
    def is_floating_point(self) -> bool: ...
    def is_complex(self) -> bool: ...
    def isnan(self) -> TensorLike: ...
    def isinf(self) -> TensorLike: ...
    def any(self) -> bool: ...

class Validator(ABC, metaclass=abc.ABCMeta):
    """Validates  data and constraints."""
    @abstractmethod
    def validate(self, data: Any) -> None: ...

def register_validator(data_type: type): ...
ValidatorCallable = Callable[[Any], None]

def compose_validators(*validators: ValidatorCallable) -> ValidatorCallable: ...
def all_of(validators: list[ValidatorCallable]) -> ValidatorCallable: ...
def any_of(validators: list[ValidatorCallable]) -> ValidatorCallable: ...
@singledispatch
def validate_series(series: Any, name: str = 'series') -> None: ...
@singledispatch
def validate_ohlcv(df: Any) -> None: ...
@singledispatch
def validate_stream_chunk(chunk: Any) -> None: ...
def validate_data_for_training(df: Any) -> None: ...
def validate_symbol(symbol: Any) -> None: ...
def validate_date(date: Any) -> None: ...
@singledispatch
def validate_tensor(tensor: Any, *, ndim: int | None = None, name: str = 'tensor') -> None: ...

class CustomSeriesValidator(Validator):
    """Validates custom series data and constraints."""
    min_length: Incomplete = ...
    def __init__(self, min_length: int = 0) -> None: ...
    def validate(self, data: pd.Series) -> None: ...

@singledispatch
def validate_file_data(data: Any, format: str) -> None: ...