import pandas as pd
import tensorflow as tf
from typing import Any

__all__ = ['validate_series', 'validate_dataframe', 'validate_data_for_training', 'validate_symbol', 'validate_date', 'validate_tensor']

def validate_series(series: pd.Series, name: str = 'series') -> None: ...
def validate_dataframe(df: pd.DataFrame, min_columns: int = 1) -> None: ...
def validate_tensor(tensor: tf.Tensor, name: str = 'tensor', min_dims: int = 1) -> None: ...
def validate_data_for_training(data: pd.DataFrame) -> None: ...
def validate_symbol(symbol: Any) -> None: ...
def validate_date(date: str | None) -> None: ...
