import logging
import polars as pl
from srcPy.ops.mm_logkit import get_logger as get_logger
from srcPy.utils.exceptions import DataError as DataError, DataFetchError as DataFetchError, DataValidationError as DataValidationError, PreprocessingError as PreprocessingError
from typing import Any, Callable

def retry_async(retries: int = 3, backoff_factor: float = 0.5, exceptions: tuple[type[BaseException], ...] = ..., jitter: float = 0.2) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def normalize_dataframe(df: Any, schema: dict[str, pl.DataType] | None = None, engine: str = 'polars') -> pl.DataFrame: ...
def ensure_lazy(df: Any, *, schema: dict[str, pl.DataType] | None = None) -> pl.LazyFrame: ...
def setup_logger(name: str, level: int = ..., fmt: str = '%(asctime)s - %(name)s - %(levelname)s - %(message)s') -> logging.Logger: ...