from typing import Any

def canonical_op(op_id: str, aliases: dict[str, str]) -> str: ...
def normalize_common_keys(o: dict[str, Any]) -> dict[str, Any]: ...
def normalize_input(o: dict[str, Any]) -> dict[str, Any]: ...
def normalize_clip(o: dict[str, Any]) -> dict[str, Any]: ...
def ensure_list(o: dict[str, Any], key: str) -> dict[str, Any]: ...
def map_fill_strategy(val: str) -> str: ...
def normalize_lag(o: dict[str, Any]) -> dict[str, Any]: ...
def normalize_bucket(o: dict[str, Any]) -> dict[str, Any]: ...
def assign_device_hint(o: dict[str, Any]) -> dict[str, Any]: ...
