from _typeshed import Incomplete
from srcPy.ops.observability import get_metrics as get_metrics, instrument as instrument
from srcPy.utils.capability_manager import HAS as HAS
from srcPy.utils.dependency_manager import deps as deps
from typing import Any, Callable

class PipelineMetricsError(Exception): ...
class MLflowUnavailable(PipelineMetricsError): ...

ERROR_COUNTER: Incomplete
STEP_EXECUTION_TIME: Incomplete
mlflow: Incomplete

class AsyncMLflowLogger:
    def __init__(self) -> None: ...
    async def log_metrics(self, metrics: dict[str, float], *, step: int | None = None) -> None: ...
    async def log_params(self, params: dict[str, Any]) -> None: ...
    async def set_experiment(self, name: str) -> None: ...
    async def start_run(self, *, run_name: str | None = None, nested: bool = True, tags: dict[str, str] | None = None) -> Any: ...
    async def end_run(self) -> None: ...
    async def log_artifact(self, local_path: str, *, artifact_path: str | None = None) -> None: ...

def track_step_execution(step_name: str, *, stage: str = 'unknown', engine: str = 'unknown'): ...
def wire_streaming_observers(get_buffer_len: Callable[[], int] | None, get_processed_volume: Callable[[], int] | None) -> None: ...
