from .pipeline_core_registry import StepRegistry as StepRegistry
from typing import Iterable

def load_stage_plugins(stage: str, group_prefix: str = 'marketmind'): ...
def discover_all_plugins(stages: Iterable[str], group_prefix: str = 'marketmind'): ...