# from .pipeline_core_base import PipelineGraphError as PipelineGraphError, PipelineStep as PipelineStep  # stripped for AutoAPI
# from .pipeline_core_context import PipelineContext as PipelineContext  # stripped for AutoAPI
from typing import Any as Incomplete
from typing import Any

def choose_combo(cfg, ctx, name: str = None): ...
def topo_order(steps: list[str], order_cfg: dict[str, dict[str, list[str]]]) -> list[str]: ...

class PipelineBuilder:
    """Builder for constructing pipeline objects."""
    stage: Incomplete = ...
    config: Incomplete = ...
    steps: list[Any] = ...
    def __init__(self, stage: str, config: dict[str, Any] | None = None) -> None: ...
    @classmethod
    def for_stage(cls, stage: str, config: dict[str, Any] | None = None) -> PipelineBuilder: ...
    def from_preset_and_params(self, preset: dict[str, Any], params: dict[str, Any]) -> PipelineBuilder: ...
    def add_steps(self, steps): ...
    def build(self) -> Pipeline: ...
    def validate_contracts(self) -> PipelineBuilder: ...

class Pipeline:
    """pipeline class."""
    steps: Incomplete = ...
    config: Incomplete = ...
    def __init__(self, steps: list[PipelineStep], config: dict[str, Any]) -> None: ...
    def fit_transform(self, df): ...