from typing import Any as Incomplete
from srcPy.ops.observability import get_metrics as get_metrics
from srcPy.utils.dependency_manager import deps as deps
from typing import Any, Callable

class CleaningMetricsError(Exception): ...
class MLflowUnavailable(CleaningMetricsError): ...

mlflow: Incomplete = ...

class AsyncMLflowLogger:
    """async m lflow logger class."""
    def __init__(self) -> None: ...
    async def log_metrics(self, metrics: dict[str, float], *, step: int | None = None) -> None: ...
    async def log_params(self, params: dict[str, Any]) -> None: ...
    async def set_experiment(self, name: str) -> None: ...
    async def start_run(self, *, run_name: str | None = None, nested: bool = True, tags: dict[str, str] | None = None) -> Any: ...
    async def end_run(self) -> None: ...
    async def log_artifact(self, local_path: str, *, artifact_path: str | None = None) -> None: ...

async def log_metric_mlflow(key: str, value: Any) -> None: ...
def record_step_latency_ms(value_ms: float, *, step: str = 'unknown') -> None: ...
def wire_cleaner_observers(*, get_latency: Callable[[], float] | None, get_buffer_len: Callable[[], int] | None, get_data_volume: Callable[[], int] | None) -> None: ...