from .factory import resolve_name as resolve_name
from .graph import Graph as Graph
from .ops import Op as Op, OpKind as OpKind
from typing import Any, Callable

class BackendAwareOp(Op):
    backend_hint: str | None
    def __init__(self, **params: Any) -> None: ...
    def to_ir(self) -> dict[str, Any]: ...

class OpFactory:
    @staticmethod
    def create(op_symbol: str, **params: Any) -> Op: ...

def op(op_symbol: str, backend_hint: str | None = None, **params: Any) -> Op: ...
def sequence(*ops: Op | str | dict[str, Any]) -> Graph: ...
def parallel(*subgraphs: Graph | Op | str | dict[str, Any]) -> Graph: ...
def __rshift__(self, other: Op | str | dict[str, Any] | Graph) -> Graph: ...
def __or__(self, other: Op | str | dict[str, Any] | Graph) -> Graph: ...
def combine_ops(name: str, *sub_ops: Op, backend_selector: Callable[[list[Op]], str] = ...) -> type[Op]: ...
