from typing import Any as Incomplete
from abc import ABC, ABCMeta, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, Sequence

__all__ = ['Expr', 'Column', 'Literal', 'OpExpr', 'expr_factory', 'register_expr', 'register_builtin_builders', 'ExprMeta']

def register_expr(op: str, builder: Callable[..., Expr]) -> None: ...

class ExprMeta(ABCMeta):
    """expr meta class."""
    def __new__(cls, name, bases, dct): ...

class Expr(ABC, metaclass=ExprMeta):
    """expr class."""
    op: str | None
    args: Sequence['Expr']
    params: dict[str, Any]
    def __init__(self, args: Sequence['Expr'] = (), params: dict[str, Any] = None) -> None: ...
    def validate(self) -> None: ...
    def __add__(self, other: Expr | Any) -> Expr: ...
    def __sub__(self, other: Expr | Any) -> Expr: ...
    def __mul__(self, other: Expr | Any) -> Expr: ...
    def __truediv__(self, other: Expr | Any) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __pow__(self, other: Expr | Any) -> Expr: ...
    def __radd__(self, other: Expr | Any) -> Expr: ...
    def __rsub__(self, other: Expr | Any) -> Expr: ...
    def __rmul__(self, other: Expr | Any) -> Expr: ...
    def __rtruediv__(self, other: Expr | Any) -> Expr: ...
    def __rpow__(self, other: Expr | Any) -> Expr: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    @abstractmethod
    def to_ir(self) -> dict[str, Any]: ...
    def optimize(self) -> Expr: ...

@dataclass(frozen=True)
class Column(Expr):
    """column class."""
    op = ...
    name: str
    def __init__(self, name: str) -> None: ...
    def validate(self) -> None: ...
    def to_ir(self) -> dict[str, Any]: ...

@dataclass(frozen=True)
class Literal(Expr):
    """literal class."""
    op = ...
    value: Any
    def __init__(self, value: Any) -> None: ...
    def to_ir(self) -> dict[str, Any]: ...

class OpExpr(Expr):
    """op expr class."""
    op: Incomplete
    def __init__(self, op: str, args: Sequence[Expr | Any], params: dict[str, Any] = None) -> None: ...
    def to_ir(self) -> dict[str, Any]: ...
    def optimize(self) -> Expr: ...

def expr_factory(op: str, args: Sequence[Expr | Any] = (), **params: Any) -> Expr: ...
def register_builtin_builders() -> None: ...