from dataclasses import dataclass
from srcPy.preprocessor.graph.graph import Graph as Graph
from srcPy.preprocessor.graph.ops import Op as Op
from srcPy.preprocessor.utils.errors import UnsupportedAST as UnsupportedAST
from srcPy.preprocessor.utils.expr_builders import ExprFactory as ExprFactory
from srcPy.preprocessor.utils.transforms import TransformFactory as TransformFactory
from srcPy.utils.exceptions import UnsupportedPlan as UnsupportedPlan
from typing import Any

@dataclass(frozen=True)
class OpSpec:
    """op spec class."""
    name: str = ...
    params: dict[str, Any] = ...

def register(name: str, op_cls: type[Op]) -> None: ...
def register_alias(alias: str, target: str) -> None: ...
def resolve_name(name: str) -> str: ...
def build_graph(ops: list[str], params: dict[str, list[dict[str, Any]]]) -> Graph: ...
def registry_snapshot() -> tuple[dict[str, str], dict[str, str]]: ...
def register_builtin_ops() -> None: ...