from dataclasses import dataclass
from srcPy.preprocessor.graph.graph import Graph
from srcPy.preprocessor.graph.ops import Op as Op
from typing import Any

@dataclass(frozen=True)
class OpSpec:
    name: str
    params: dict[str, Any]

def register(name: str, op_cls: type[Op]) -> None: ...
def register_alias(alias: str, target: str) -> None: ...
def resolve_name(name: str) -> str: ...
def build_graph(ops: list[str], params: dict[str, list[dict[str, Any]]]) -> Graph: ...
def registry_snapshot() -> tuple[dict[str, str], dict[str, str]]: ...
def register_builtin_ops() -> None: ...
