from srcPy.preprocessor.graph.expr import register_polars_lowering as register_polars_lowering
from srcPy.preprocessor.graph.ops import ElementwiseOp as ElementwiseOp, RollingOp as RollingOp, ScalingOp as ScalingOp, SequenceOp as SequenceOp
from typing import Any

class RSI(RollingOp):
    """rsi class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def to_ir(self) -> dict[str, Any]: ...

class SMA(RollingOp):
    """sma class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def to_ir(self) -> dict[str, Any]: ...

class Lags(SequenceOp):
    """lags class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...

class ZScore(ScalingOp):
    """z score class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def state_dict(self) -> dict[str, Any]: ...

class RobustScaler(ScalingOp):
    """robust scaler class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def state_dict(self) -> dict[str, Any]: ...

class SentimentLexicon(ElementwiseOp):
    """sentiment lexicon class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...

class PairBeta(RollingOp):
    """pair beta class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class PairSpread(ElementwiseOp):
    """pair spread class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class HalfLife(RollingOp):
    """half life class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class RollingZ(ScalingOp):
    """rolling z class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class RollingVol(RollingOp):
    """rolling vol class."""
    NAME: str = ...
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

def lower_pairs_beta_polars(*args, **kwargs) -> None: ...
def lower_pairs_spread_polars(*args, **kwargs) -> None: ...
def lower_half_life_polars(*args, **kwargs) -> None: ...
def lower_zscore_roll_polars(*args, **kwargs) -> None: ...
def lower_rolling_vol_polars(*args, **kwargs) -> None: ...