from srcPy.preprocessor.graph.ops import ElementwiseOp, RollingOp, ScalingOp, SequenceOp
from typing import Any

class RSI(RollingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def to_ir(self) -> dict[str, Any]: ...

class SMA(RollingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def to_ir(self) -> dict[str, Any]: ...

class Lags(SequenceOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...

class ZScore(ScalingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def state_dict(self) -> dict[str, Any]: ...

class RobustScaler(ScalingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...
    def state_dict(self) -> dict[str, Any]: ...

class SentimentLexicon(ElementwiseOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self) -> set[str]: ...
    def provides(self) -> set[str]: ...

class PairBeta(RollingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class PairSpread(ElementwiseOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class HalfLife(RollingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class RollingZ(ScalingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

class RollingVol(RollingOp):
    NAME: str
    def validate_params(self) -> None: ...
    def requires(self): ...
    def provides(self): ...

def lower_pairs_beta_polars(*args, **kwargs) -> None: ...
def lower_pairs_spread_polars(*args, **kwargs) -> None: ...
def lower_half_life_polars(*args, **kwargs) -> None: ...
def lower_zscore_roll_polars(*args, **kwargs) -> None: ...
def lower_rolling_vol_polars(*args, **kwargs) -> None: ...
