from _typeshed import Incomplete
from srcPy.data.data_loader import build_loader as build_loader
from srcPy.strategies.baseStrategies import BaseStrategy as BaseStrategy
from srcPy.utils.backtester_bt import Backtester as Backtester
from srcPy.utils.exceptions import DataValidationError as DataValidationError, InvalidInputError as InvalidInputError, StatisticalTestError as StatisticalTestError
from srcPy.utils.logger import get_logger as get_logger
from srcPy.utils.validators import validate_data_for_training as validate_data_for_training

logger: Incomplete

def load_data(start_date, end_date): ...
def run_single_backtest(regime, start, end, model, initial_cash, commission, position_size, riskfreerate, seed): ...
def run_backtests(model, regimes, initial_cash: int = 100000, commission: float = 0.001, position_size: float = 1.0, riskfreerate: float = 0.02, num_seeds: int = 30, max_workers: int = 4): ...
def statistical_tests(results): ...
def load_regimes(config_file: Incomplete | None = None): ...
def main(model): ...
