from _typeshed import Incomplete

logger: Incomplete

def register(backend: str, op: str, fn): ...
def get(backend: str, op: str): ...
def list_ops(backend: str = None) -> list[str]: ...
def auto_register_from_utils(): ...
