from typing import Any as Incomplete
from srcPy.domain.interfaces import Order as Order, OrderExecutor as OrderExecutor

class IBKROrderExecutor(OrderExecutor):
    """ibkr order executor class."""
    cfg: Incomplete = ...
    def __init__(self, conn_cfg) -> None: ...
    def submit(self, order: Order) -> str: ...
    def cancel(self, order_id: str) -> None: ...
    def status(self, order_id: str) -> str: ...