from _typeshed import Incomplete
from srcPy.data.data_loader import build_loader as build_loader

class DataLoader:
    @staticmethod
    def fetch_alpha(symbol, **kwargs): ...

class LogisticRegressionStrategy: ...
class RandomForestStrategy: ...
class ARIMAStrategy: ...
class GARCHStrategy: ...
class MovingAverageCrossover: ...
class RSIStrategy: ...
class MACDStrategy: ...
class BollingerStrategy: ...

class Backtester:
    def __init__(self, *_a, **_k) -> None: ...
    def run(self, *_a, **_k): ...

strategies: Incomplete
regimes: Incomplete
results: Incomplete
data: Incomplete
data_slice: Incomplete
backtester: Incomplete
metrics: Incomplete
df: Incomplete
