import torch
import torch.nn as nn
from _typeshed import Incomplete
from dataclasses import dataclass
from srcPy.models.LSTM_model import LSTMConfig
from typing import Any, Mapping

log: Incomplete

@dataclass
class ClassifierConfig(LSTMConfig):
    num_classes: int = ...
    projection_dim: int | None = ...
    pooling_type: str | None = ...
    @classmethod
    def from_marketmind(cls, overrides: Mapping[str, Any] | None = None) -> ClassifierConfig: ...

class LSTMClassifier(nn.Module):
    config: Incomplete
    lstm_block: Incomplete
    projection: Incomplete
    classifier: Incomplete
    def __init__(self, config: ClassifierConfig | None = None) -> None: ...
    def num_parameters(self, trainable_only: bool = True) -> int: ...
    def forward(self, x: torch.Tensor, lengths: torch.Tensor | None = None) -> torch.Tensor: ...
    def predict_proba(self, x: torch.Tensor, lengths: torch.Tensor | None = None) -> torch.Tensor: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def from_pretrained(cls, path: str, map_location: str | torch.device = 'cpu') -> LSTMClassifier: ...
