import polars as pl
# from .contracts import MarketDataFrameSchema as MarketDataFrameSchema  # stripped for AutoAPI
from typing import Any as Incomplete
from srcPy.ops.mm_logkit import get_logger as get_logger
from srcPy.pipeline.core.pipeline_core_metrics import AsyncMLflowLogger as AsyncMLflowLogger
from srcPy.pipeline.stages.cleaning.core.base import CleaningStep as CleaningStep
from srcPy.utils.exceptions import DataValidationError as DataValidationError
from srcPy.utils.validators import validate_dataframe as validate_dataframe, validate_ohlcv as validate_ohlcv

logger: Incomplete = ...

class ValidationStep(CleaningStep):
    """validation step class."""
    mlflow_logger: Incomplete = ...
    required_columns: Incomplete = ...
    ohlcv_mode: Incomplete = ...
    schema: Incomplete = ...
    strict: Incomplete = ...
    def __init__(self, mlflow_logger: AsyncMLflowLogger, required_columns: list[str] | None = None, ohlcv_mode: bool = False, schema: MarketDataFrameSchema | None = None, strict: bool = True) -> None: ...
    def apply(self, df: pl.DataFrame) -> pl.DataFrame: ...
    def __del__(self) -> None: ...