import abc
import polars as pl
from typing import Any as Incomplete
from abc import ABC, abstractmethod
from typing import Any, AsyncIterator

class DataSource(ABC, metaclass=abc.ABCMeta):
    """data source class."""
    config: Incomplete = ...
    def __init__(self, config: dict[str, Any]) -> None: ...
    @abstractmethod
    async def get_historical(self, symbol: str, start: str, end: str, *, eager: bool = False) -> pl.LazyFrame | pl.DataFrame: ...
    @abstractmethod
    async def get_realtime(self, symbol: str, *, interval: float = 60.0) -> AsyncIterator[pl.DataFrame]: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def close(self) -> None: ...

class APIDataSource(DataSource, metaclass=abc.ABCMeta):
    """api data source class."""
    session: Incomplete = ...
    def __init__(self, config: dict[str, Any]) -> None: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
    async def close(self) -> None: ...