import abc
from _typeshed import Incomplete
from srcPy.pipeline.core.pipeline_core_base import CleaningStep
from srcPy.pipeline.core.pipeline_core_metrics import AsyncMLflowLogger as AsyncMLflowLogger

KalmanFilter: Incomplete
logger: Incomplete

class _NullLogger:
    def log_metric(self, key, value) -> None: ...
    def close(self) -> None: ...

class BaseMissingImputer(CleaningStep, metaclass=abc.ABCMeta):
    mlflow_logger: Incomplete
    method: Incomplete
    params: Incomplete
    supported_methods: Incomplete
    def __init__(self, method: str = 'forward_fill', params: dict | None = None, mlflow_logger: AsyncMLflowLogger | None = None, **_) -> None: ...
    def apply(self, df): ...
    def __del__(self) -> None: ...

class MissingValueNormalizerStep(BaseMissingImputer): ...
class MissingImputer(MissingValueNormalizerStep): ...
