import numpy as np
import polars as pl
from typing import Any as Incomplete
from srcPy.ops.mm_logkit import get_logger as get_logger
from srcPy.pipeline.core.pipeline_core_base import CleaningStep as CleaningStep
from srcPy.pipeline.core.pipeline_core_metrics import AsyncMLflowLogger as AsyncMLflowLogger
from srcPy.utils.exceptions import DataValidationError as DataValidationError

logger: Incomplete = ...

class _NullLogger:
    """null logger class."""
    def log_metric(self, key, value) -> None: ...
    def close(self) -> None: ...

def efficient_outlier_mask(num: np.ndarray, threshold: float) -> np.ndarray: ...

class BaseOutlierHandler(CleaningStep):
    """Handles base outlier events and requests."""
    mlflow_logger: Incomplete = ...
    method: Incomplete = ...
    params: Incomplete = ...
    supported_methods: Incomplete = ...
    def __init__(self, method: str = 'zscore', params: dict | None = None, mlflow_logger: AsyncMLflowLogger | None = None, **_) -> None: ...
    def apply(self, df: pl.DataFrame) -> pl.DataFrame: ...
    def __del__(self) -> None: ...

class OutlierNormalizerStep(BaseOutlierHandler): ...
class OutlierHandler(OutlierNormalizerStep): ...