import abc
from .cuda_runtime import capabilities as capabilities
from .errors import SchemaMismatch as SchemaMismatch, UnsupportedAST as UnsupportedAST
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from typing import Callable, Iterable

logger: Incomplete

class ColumnOp(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def apply(self, df, cols: Iterable[str], **kwargs): ...
    def validate(self, df, cols: Iterable[str]) -> None: ...

def profile_op(func: Callable) -> Callable: ...

class CastNumeric(ColumnOp):
    @profile_op
    def apply(self, df, cols: Iterable[str], dtype: str = 'float32'): ...

class PromoteCategorical(ColumnOp):
    @profile_op
    def apply(self, df, cols: Iterable[str], ordered: bool = False, **kwargs): ...

class ColumnOpFactory:
    registry: dict[str, Callable[..., ColumnOp]]
    @classmethod
    def register(cls, name: str, op_class: Callable[..., ColumnOp]): ...
    @classmethod
    def build(cls, name: str, **kwargs) -> ColumnOp: ...

def op_chain(*op_names: str, **kwargs) -> Callable: ...
def live_after(cols: Iterable[str]) -> list[str]: ...
def ensure_unique(cols: Iterable[str], sep: str = '__') -> list[str]: ...
def save_metrics(file: str = 'metrics.json'): ...
