# from .cuda_runtime import capabilities as capabilities  # stripped for AutoAPI
# from .errors import UnsupportedAST as UnsupportedAST  # stripped for AutoAPI
from typing import Any as Incomplete
from typing import Any, Callable

def register_expr(name: str, builder: Callable[..., Any]) -> None: ...

class Expr:
    """expr class."""
    func: Incomplete = ...
    def __init__(self, func: Callable[[Any], Any]) -> None: ...
    def __add__(self, other: Expr) -> Expr: ...

class ExprFactory:
    """Factory for creating expr instances."""
    registry: dict[str, Callable[..., Any]] = ...
    @classmethod
    def register(cls, name: str, builder: Callable[..., Any]) -> None: ...
    @classmethod
    def build(cls, name: str, **kwargs: Any) -> Any: ...

def safe_div_builder(eps: float = 1e-12, backend: str = 'polars') -> Callable[[Any, Any], Any]: ...
def zscore_builder(col: str, mean: Any | None = None, std: Any | None = None, backend: str = 'polars') -> Callable[[Any], Any]: ...
def bollinger_builder(col: str, window: int = 20, num_std: float = 2.0, backend: str = 'polars') -> Callable[[Any], Any]: ...