from _typeshed import Incomplete
from dataclasses import dataclass
from srcPy.utils.optional_imports import cudf, pl as polars
from typing import Any, Literal

logger: Incomplete
NVCOMP_CODECS: Incomplete
Frame = Any

@dataclass
class ParquetOptions:
    columns: list[str] | None = ...
    compression: Literal['snappy', 'zstd', 'lz4', 'none'] | None = ...
    filters: Any | None = ...
    engine: Literal['cudf', 'polars'] | None = ...

def read_parquet_gpu(path: str | list[str], opts: ParquetOptions | None = None) -> Frame: ...
def write_parquet_gpu(df: Frame, path: str, opts: ParquetOptions | None = None, **kwargs: Any) -> None: ...
