import abc
from typing import Any as Incomplete
from abc import ABC, abstractmethod
from datetime import datetime
from srcPy.ops.mm_logkit import get_logger as get_logger
from typing import Callable

logger: Incomplete = ...

class MarketCalendar(ABC, metaclass=abc.ABCMeta):
    """market calendar class."""
    @abstractmethod
    def is_open_at(self, ts: datetime) -> bool: ...
    @abstractmethod
    def next_open(self, ts: datetime) -> datetime: ...
    @abstractmethod
    def next_close(self, ts: datetime) -> datetime: ...

class FallbackCalendar(MarketCalendar):
    """fallback calendar class."""
    def is_open_at(self, ts: datetime) -> bool: ...
    def next_open(self, ts: datetime) -> datetime: ...
    def next_close(self, ts: datetime) -> datetime: ...

def profile_calendar(func: Callable) -> Callable: ...

class MarketCalendarFactory:
    """Factory for creating market calendar instances."""
    cal: Incomplete = ...
    @staticmethod
    def get_calendar(exchange: str = 'NYSE') -> MarketCalendar: ...

def is_session(ts: datetime | None = None, cal: MarketCalendar | None = None) -> bool: ...
def next_session(ts: datetime | None = None, cal: MarketCalendar | None = None) -> datetime: ...
def time_bucket(ts: datetime, seconds: int) -> datetime: ...
def resample_ohlcv(df, ts_col: str, seconds: int, engine: str | None = None): ...