import contextlib
import types
from typing import Any as Incomplete
from srcPy.ops.mm_logkit import get_logger as get_logger

logger: Incomplete = ...
NVTX_ENABLED: Incomplete = ...

@contextlib.contextmanager
def range_ctx(message: str, color: int | None = None): ...
def nvtx_range(message: str, color: int | None = None): ...

class nvtx_plan:
    """nvtx plan class."""
    name: Incomplete = ...
    color: Incomplete = ...
    def __init__(self, name: str, color: int | None = None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: types.TracebackType | None) -> None: ...