from typing import Any as Incomplete
from typing import Any, Mapping

def autotune(objective_fn, search_space: Mapping[str, Any], *, budget: int = 10, seed: int | None = None) -> dict[str, Any]: ...

class AutoTuner:
    """auto tuner class."""
    search_space: Incomplete = ...
    metric: Incomplete = ...
    budget: Incomplete = ...
    seed: Incomplete = ...
    def __init__(self, search_space: Mapping[str, Any] | None = None, *, metric: str | None = None, budget: int = 10, seed: int | None = None) -> None: ...
    def run(self, objective_fn) -> dict[str, Any]: ...
    def evaluate(self, df_prices, preproc_spec, params) -> dict[str, Any]: ...
    def tune(self, df_prices, preproc_spec) -> dict[str, Any]: ...